// Fantasy Keeper Commissioner — Mock Data
window.APP_DATA = {
  leagues: [
    {
      id: 'hockey-1',
      name: 'The Pond',
      sport: 'hockey',
      draftType: 'snake',
      season: '2026-27',
      teamCount: 12,
      keeperSlots: 4,
      minKeepers: 4,
      contractYears: 3,
      buyIn: 150,
      totalPool: 1800,
      status: 'pre-draft',
      draftDate: '2026-10-01',
      playoffTeams: 8,
      bottomLotteryTeams: 4,
      noPlayoffPickupKeepers: true,
      contractsRequired: true,
      payouts: [
        { label: 'Regular Season — 1st', amount: 750 },
        { label: 'Regular Season — 2nd', amount: 150 },
        { label: 'Playoffs — 1st', amount: 450 },
        { label: 'Playoffs — 2nd', amount: 300 },
        { label: 'Playoffs — 3rd', amount: 150 },
      ],
      payoutNote: 'If the same team wins the regular season and playoffs, the entire $1,800 pool goes to that team.',
      teams: [
        { id: 't1', name: 'Mark', paid: true, paidDate: '2025-09-12', paidNote: 'EMT', keepersSubmitted: false, keepers: [],
          rosterAsOfDate: '2026-03-10',
          roster: [
            { player: 'Tim Stützle', pos: 'C' },
            { player: 'Nico Hischier', pos: 'C' },
            { player: 'Lane Hutson', pos: 'D' },
            { player: 'Jack Hughes', pos: 'C' },
            { player: 'Boone Jenner', pos: 'LW' },
            { player: 'Travis Konecny', pos: 'LW' },
            { player: 'Matt Boldy', pos: 'RW' },
            { player: 'David Pastrnak', pos: 'RW' },
            { player: 'Thomas Harley', pos: 'D' },
            { player: 'Moritz Seider', pos: 'D' },
            { player: 'Evan Bouchard', pos: 'D' },
            { player: 'Alex Pietrangelo', pos: 'D' },
            { player: 'Sam Bennett', pos: 'Util' },
            { player: 'Noah Dobson', pos: 'BN' },
            { player: 'Juraj Slafkovský', pos: 'BN' },
            { player: 'Dylan Guenther', pos: 'BN' },
            { player: 'Kevin Lankinen', pos: 'G' },
            { player: 'Mackenzie Blackwood', pos: 'G' },
          ],
          priorKeepers: [
          { player: 'Tim Stützle', contractYear: 2, contractLength: 3, note: 'Kept last 2 yrs' },
          { player: 'Matthew Tkachuk', contractYear: 1, contractLength: 3 },
          { player: 'Lane Hutson', contractYear: 0, contractLength: 3, note: 'Drafted last year, eligible Y1' },
          { player: 'Jack Hughes', contractYear: 3, contractLength: 3, expired: true, note: 'Contract expired — back to draft' },
        ] },
        { id: 't2', name: 'Amar', paid: true, paidDate: '2025-09-15', paidNote: 'EMT', keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Connor Hellebuyck', contractYear: 0, contractLength: 3 },
          { player: 'Leon Draisaitl', contractYear: 2, contractLength: 3 },
          { player: 'Quinn Hughes', contractYear: 1, contractLength: 3 },
          { player: 'William Nylander', contractYear: 2, contractLength: 3, note: 'Acquired from Mack mid-season' },
        ] },
        { id: 't3', name: 'Andrew', paid: true, paidDate: '2025-09-18', paidNote: 'Cash at draft', keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Artemi Panarin', contractYear: 1, contractLength: 3 },
          { player: 'Sam Reinhart', contractYear: 1, contractLength: 3 },
          { player: 'Wyatt Johnston', contractYear: 0, contractLength: 3 },
          { player: 'Jacob Markstrom', contractYear: 1, contractLength: 3 },
        ] },
        { id: 't4', name: 'Ben', paid: false, keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Connor McDavid', contractYear: 2, contractLength: 3 },
          { player: 'Cale Makar', contractYear: 0, contractLength: 3 },
          { player: 'Jake Oettinger', contractYear: 0, contractLength: 3 },
          { player: 'Victor Hedman', contractYear: 0, contractLength: 3 },
        ] },
        { id: 't5', name: 'Corey', paid: true, paidDate: '2025-09-20', keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Aleksander Barkov', contractYear: 2, contractLength: 3 },
          { player: 'Mark Scheifele', contractYear: 1, contractLength: 3 },
          { player: 'Alex Ovechkin', contractYear: 2, contractLength: 3 },
          { player: 'Rob Thomas', contractYear: 0, contractLength: 3 },
        ] },
        { id: 't6', name: 'Mack', paid: false, keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Sidney Crosby', contractYear: 1, contractLength: 3 },
          { player: 'Kyle Connor', contractYear: 0, contractLength: 3 },
          { player: 'Seth Jarvis', contractYear: 0, contractLength: 3 },
          { player: 'Nathan MacKinnon', contractYear: 2, contractLength: 3, note: 'Traded William Nylander to Amar for picks' },
        ] },
        { id: 't7', name: 'Kyle', paid: true, paidDate: '2025-09-22', paidNote: 'EMT', keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Nikita Kucherov', contractYear: 1, contractLength: 3 },
          { player: 'David Pastrnak', contractYear: 2, contractLength: 3 },
          { player: 'Brayden Point', contractYear: 2, contractLength: 3 },
          { player: 'Mikko Rantanen', contractYear: 2, contractLength: 3 },
        ] },
        { id: 't8', name: 'Mitch', paid: false, keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Auston Matthews', contractYear: 1, contractLength: 3 },
          { player: 'Mitch Marner', contractYear: 0, contractLength: 3 },
          { player: 'Igor Shesterkin', contractYear: 1, contractLength: 3 },
        ] },
        { id: 't9', name: 'Nick', paid: false, keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Sebastian Aho', contractYear: 0, contractLength: 3 },
          { player: 'Roman Josi', contractYear: 1, contractLength: 3 },
        ] },
        { id: 't10', name: 'Pedram', paid: false, keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Jason Robertson', contractYear: 1, contractLength: 3 },
          { player: 'Adin Hill', contractYear: 0, contractLength: 3 },
          { player: 'Tage Thompson', contractYear: 0, contractLength: 3 },
        ] },
        { id: 't11', name: 'Scott', paid: false, keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Jesper Bratt', contractYear: 0, contractLength: 3 },
        ] },
        { id: 't12', name: 'Will', paid: false, keepersSubmitted: false, keepers: [], priorKeepers: [
          { player: 'Mathew Barzal', contractYear: 1, contractLength: 3 },
          { player: 'Filip Forsberg', contractYear: 0, contractLength: 3 },
        ] },
      ]
    },
    {
      id: 'basketball-1',
      name: 'Hardwood Hustle',
      sport: 'basketball',
      draftType: 'auction',
      season: '2026-27',
      teamCount: 12,
      keeperSlots: 4,
      minKeepers: 0,
      buyIn: 100,
      totalPool: 1200,
      status: 'pre-draft',
      draftDate: '2026-10-20',
      playoffTeams: 6,
      noPlayoffPickupKeepers: true,
      auctionRules: {
        costIncreasePerYear: 5,
        undraftedStartCost: 5,
        lastPlacePenalty: 50,
        minBid: 1,
      },
      payouts: [
        { label: '1st Place', amount: 600 },
        { label: '2nd Place', amount: 300 },
        { label: '3rd Place', amount: 150 },
        { label: 'Last Place (penalty)', amount: -50 },
      ],
      payoutNote: 'Last place team pays an extra $50 to discourage tanking late in the season.',
      teams: [
        { id: 'b1', name: 'Team Alpha', paid: true, keepersSubmitted: true, keepers: [
          { player: 'Nikola Jokic', keptFor: 42, yearsKept: 3 },
          { player: 'Luka Doncic', keptFor: 28, yearsKept: 2 },
          { player: 'Shai Gilgeous-Alexander', keptFor: 16, yearsKept: 1 },
        ]},
        { id: 'b2', name: 'Team Beta', paid: true, keepersSubmitted: true, keepers: [
          { player: 'Giannis Antetokounmpo', keptFor: 33, yearsKept: 2 },
          { player: 'Anthony Davis', keptFor: 21, yearsKept: 1 },
        ]},
        { id: 'b3', name: 'Team Gamma', paid: false, keepersSubmitted: false, keepers: [] },
        { id: 'b4', name: 'Team Delta', paid: true, keepersSubmitted: true, keepers: [
          { player: 'Joel Embiid', keptFor: 18, yearsKept: 1 },
          { player: 'Damian Lillard', keptFor: 12, yearsKept: 1 },
          { player: 'Draymond Green', keptFor: 9, yearsKept: 1 },
          { player: 'Devin Booker', keptFor: 14, yearsKept: 1 },
        ]},
        { id: 'b5', name: 'Team Epsilon', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'b6', name: 'Team Zeta', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'b7', name: 'Team Eta', paid: false, keepersSubmitted: false, keepers: [] },
        { id: 'b8', name: 'Team Theta', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'b9', name: 'Team Iota', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'b10', name: 'Team Kappa', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'b11', name: 'Team Lambda', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'b12', name: 'Team Mu', paid: true, keepersSubmitted: true, keepers: [
          { player: 'LeBron James', keptFor: 47, yearsKept: 4 },
        ]},
      ]
    },
    {
      id: 'football-1',
      name: 'Gridiron Glory',
      sport: 'football',
      draftType: 'auction',
      season: '2026',
      teamCount: 12,
      keeperSlots: 3,
      minKeepers: 0,
      buyIn: 100,
      totalPool: 1200,
      status: 'pre-draft',
      draftDate: '2026-08-28',
      playoffTeams: 6,
      noPlayoffPickupKeepers: true,
      auctionRules: {
        costIncreasePerYear: 5,
        undraftedStartCost: 5,
        lastPlacePenalty: 50,
        minBid: 1,
      },
      payouts: [
        { label: '1st Place', amount: 600 },
        { label: '2nd Place', amount: 300 },
        { label: '3rd Place', amount: 150 },
        { label: 'Last Place (penalty)', amount: -50 },
      ],
      payoutNote: 'Last place team pays an extra $50 to discourage tanking late in the season.',
      teams: [
        { id: 'f1', name: 'Team 1', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f2', name: 'Team 2', paid: false, keepersSubmitted: false, keepers: [] },
        { id: 'f3', name: 'Team 3', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f4', name: 'Team 4', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f5', name: 'Team 5', paid: false, keepersSubmitted: false, keepers: [] },
        { id: 'f6', name: 'Team 6', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f7', name: 'Team 7', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f8', name: 'Team 8', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f9', name: 'Team 9', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f10', name: 'Team 10', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f11', name: 'Team 11', paid: true, keepersSubmitted: false, keepers: [] },
        { id: 'f12', name: 'Team 12', paid: false, keepersSubmitted: false, keepers: [] },
      ]
    },
    {
      id: 'baseball-placeholder',
      name: 'Diamond League',
      sport: 'baseball',
      draftType: 'auction',
      season: '2027',
      teamCount: 0,
      keeperSlots: 5,
      minKeepers: 0,
      buyIn: 100,
      totalPool: 0,
      status: 'setup',
      draftDate: null,
      playoffTeams: 4,
      noPlayoffPickupKeepers: true,
      auctionRules: { costIncreasePerYear: 5, undraftedStartCost: 5, minBid: 1 },
      payouts: [],
      payoutNote: '',
      teams: []
    }
  ]
};
